### ISSUE TITLE
fireEvent_DOM: Object doesn't support property or method 'dispatchEvent'

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#119]
[previous lighthouse ticket #4459](https://prototype.lighthouseapp.com/projects/8886/tickets/4459-fireevent_dom-object-doesnt-support-property-or-method-dispatchevent) 
by Lars Brand

---

I'm using qftest (http://www.qfs.de/en/index.html) for automation of regression tests for TestLink (http://testlink.org/)
The Error-Message from qftest is:
"An error occurred inside a script on this page.

This is not a bug in QF-Test, rather the opposite: Herewith QF-Test
informs you about a potentially serious problem in your application.
Please notify the developers of the application and include the
information provided below.

Line: 6598
Character: 5
Message: Object doesn't support property or method 'dispatchEvent'
Code: 0
URL: http://1.2.3.4/testlink199/third_party/prototype/prototype.js

```
/*  Prototype JavaScript framework, version 1.7.1 */
  function fireEvent_DOM(element, eventName, memo, bubble) {
    var event = document.createEvent('HTMLEvents');
    event.initEvent('dataavailable', bubble, true);

    event.eventName = eventName;
    event.memo = memo;

    element.dispatchEvent(event);
    return event;
  }
```

**Comment by p9382** [comment]
Hi Sir, i am facing the same problem at same line. Can you please help me
