### ISSUE TITLE
Element.update resets data for a previous "select" read element in Chrome

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#128]
[previous lighthouse ticket #3527](https://prototype.lighthouseapp.com/projects/8886/tickets/3527-elementupdate-resets-data-for-a-previous-select-read-element-in-chrome) 
by Clemens Schwaighofer

***

Prototype 1.7.1.0
Chrome: 29.0.1547.65
Firefox: 23.0.1

Code HTML:

Foo 1 Foo 2
Code JS:

```
// select the input (radio) button data
var content = $('radioGroup').select('input');
// read in the HTML for this group
var target = $('radioGroup').innerHTML;
// replace the option 1 with option 3
var data_replace = new RegExp('radio_option_1', "g");
target = target.replace(data_replace, 'radio_option_3');
// pre read the select data before the update, radio button flags OK
content.each(function(v) {
    console.log('Before: ID: %s, checked: %s', v.id, v.checked);
});
// update the radioGroup div with the new changed data
$('radioGroup').update(target);
// radio button data is reset in Chrome
content.each(function(v) {
    console.log('After: ID: %s, checked: %s', v.id, v.checked);
});
}
```
Explanation:

The above script reads the input elements into a holding variable to keep the current selected stated.
Then it reads the whole div element and replaces the id from one element.
If the update is now run on the div with the new HTML data, in Chrome the previous selected element in the "content" variable is set to false. In Firefox it still shows the element as selected.

Problem:

The content from the select should not be connected to changes in the DOM.

Workaround:

For every radio element, a hash with id => state has to be created and used instead of the data from the original select read.

**Comment by savetheclocktower** [comment]
No way we can do anything about this.
