### ISSUE TITLE
Ajax.Updater.success

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#135]
[previous lighthouse ticket #3500](https://prototype.lighthouseapp.com/projects/8886/tickets/3500-ajaxupdatersuccess) 
by Alexander Lisovtsov

***

Ajax.Request.success has bug in :
```javascript
success: function() {
    var status = this.getStatus();
    return !status || (status >= 200 && status < 300) || status == 304;
},
getStatus: function() {
    try {
        if (this.transport.status === 1223) return 204;
        return this.transport.status || 0;
    } catch (e) { return 0 }
},
```
If getStatus == 0 then success function return true and Ajax.Updater every time update a success div.

On IPAD4 with IOS 6.1.3 when connection to server LOST -> Ajax.Updater update a "success" DIV with empty response.

**Comment by savetheclocktower** [comment]
Duplicate.
