### ISSUE TITLE
IE detection and opacity

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#142]
[previous lighthouse ticket #1278](https://prototype.lighthouseapp.com/projects/8886/tickets/1278-ie-detection-and-opacity) 
by Jared Fedorchuk

***

Since browser detection is used for the getStyle and setOpacity functions you run into problems with IE 9 when using the scriptaculous fade/appear affects.

It seemed to me that IE9 was using the filter\alpha and regular opacity which was causing problems. I made it so it would only modify the opacity property.

I fixed it for my purposes by changing line 2539 from

`else if (Prototype.Browser.IE) {`
to

`else if(navigator.appVersion.match(/MSIE\s+(?:6|7|8)\./)) {`
and line 2742 from

`else if (Prototype.Browser.Gecko && /rv:1\.8\.0/.test(navigator.userAgent)) {`
to

`else if (Prototype.Browser.Gecko && /rv:1\.8\.0/.test(navigator.userAgent) || document.all) {`

**Comment by savetheclocktower** [comment]
Fixed this in 9ca2e6a0445a77858d8a84588c03901c2e0b45b4.
