### ISSUE TITLE
Warning in IE when ActiveX is deactived

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#151]
[previous lighthouse ticket #2131](https://prototype.lighthouseapp.com/projects/8886/tickets/2131-Warning-in-IE-when-ActiveX-is-deactived) 
by Natasha

***

Hi everybody,

I'm really desperate - please, please I need your help:

In case that your Internet Explorer (at least in version 8 + 9) is configured NOT to allow Active-X then the following JavaScript command

document.createElement('object')
will cause a warning
An add-on for this website failed to run. Check the security settings in the Internet options for potential conflicts
.
In prototype.js that "createElement('object')" command is triggered each time the library is loaded (which is normally: always) because of the following line

var HTMLOBJECTELEMENT_PROTOTYPE_BUGGY = checkDeficiency('object');
or (depending on the prototype version)

var HTMLOBJECTELEMENT_PROTOTYPE_BUGGY = checkElementPrototypeDeficiency('object');
Am I the only one who things that this is very annoying and not a good idea?
What exactly is the reason for this HTMLOBJECTELEMENT_PROTOTYPE_BUGGY hack (it's not commented at all)?
Are there any fixes/suggestions regarding that problem?
What exactly will happen if I just replace the line above by

var HTMLOBJECTELEMENT_PROTOTYPE_BUGGY = false;
?
Thank you very much in advance for your dear help.

Hugs
Natasha

**Comment by savetheclocktower** [comment]
We ended up fixing this.
