### ISSUE TITLE
writeAttribute("draggable", true) shouldn't be translated into draggable="draggable"

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#173]
[previous lighthouse ticket #1672](https://prototype.lighthouseapp.com/projects/8886/tickets/1672-writeattributedraggable-true-shouldnt-be-translated-into-draggabledraggable) 
by Victor

***

HTML5 attributes draggable and contenteditable should have value true in order to enable corresponding action (drag or edit content, respectively), i.e.
```
<div draggable="true">drag me</div>
```
is OK, but
```
<div draggable="draggable">drag me</div>
```
isn't recognized as draggable, at least in Chrome 24. But it isn't possible to set draggable to true with Element#writeAttribute, because it translates true internally:
```
function writeAttribute(element, name, value) {
  // skipped
  else if (value === true)
    element.setAttribute(name, name);
  // skipped
}
```

**Comment by savetheclocktower** [comment]
`div.writeAttribute('draggable', 'true')` seems to work for me in Chrome.
