### ISSUE TITLE
Scriptaculous Effect.Highlight no longer works with Prototype 1.7.1

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#179]
[previous lighthouse ticket #1379](https://prototype.lighthouseapp.com/projects/8886/tickets/1379-scriptaculous-effecthighlight-no-longer-works-with-prototype-171) 
by Fjan 

***

I just noticed that upgrading Prototype from 1.7.0 to 1.7.1 breaks the often used Scriptaculous Highlight effect on all browsers I've tried. All other Scriptaculous Effects still work fine. No errors appear.

(I'm not sure if this should be reported here or on Scriptaculous, I'll report it there too, but the Prototype version number suggests it should be backwards compatible)

**Comment by savetheclocktower** [comment]
This got fixed in #59.

**Comment by savetheclocktower** [comment]
(In other words, it works with 1.7.2.)
