### ISSUE TITLE
String#toQueryParams() should be opposite to Object.toQueryString()

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#180]
[previous lighthouse ticket #1402](https://prototype.lighthouseapp.com/projects/8886/tickets/1402-stringtoqueryparams-should-be-opposite-to-objecttoquerystring) 
by Victor

***

In previous versions of Prototype String#toQueryParams() was exact opposite to Object.toQueryString(), i.e.

```
Object.toQueryString({"some name": "some value"}).toQueryParams()["some name"] === "some value";
```

It returned copy of source object. This symmetry is broken now: toQueryString() replaces spaces with + accordingly to HTML spec, but toQueryParams() does not restore them back:

```
Object.toQueryString({"some name": "some value"}).toQueryParams()["some name"] === "some+value";
```

**Comment by savetheclocktower** [comment]
This got fixed in f2a1136992a7ade837ce6c3bf43eec4381793a7a.
