### ISSUE TITLE
IE8 chokes on object and embed

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#189]
[previous lighthouse ticket #681](https://prototype.lighthouseapp.com/projects/8886/tickets/681-ie8-chokes-on-object-and-embed) 
by Nick Stakenburg

***
After testing 1.6.1_rc2 on a number of pages that use a bit event delegation IE8 started throwing errors when hovering flash movies.

To replicate add this to a page with some flash.
```
document.observe("dom:loaded", function() {
  $$("object, embed");
  document.observe('mouseover', function(event) {
    var element = event.findElement('div');
  });
});
```
Getting _countedByPrototype of an object after calling $$('object, embed') seems to throw an error, calling $(embed).ancestors() will do the same thing.

This page shows both of these problems, just move your mouse over the flash movies: http://nickstakenburg.com/tests/ie8bugs/

**Comment by savetheclocktower** [comment]
Should be fixed now.
