### ISSUE TITLE
Element#getStyle problem with IE 6 & 7

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#196]
[previous lighthouse ticket #365](https://prototype.lighthouseapp.com/projects/8886/tickets/365-elementgetstyle-problem-with-ie-6-7) 
by Michael Morris

***
I ran across this while using the Element#clonePosition function - IE will through an error about the style being null or not an object on the first call to Element#clonePosition and not on subsequent ones. Frustratingly I couldn't catch the error in outside code so I opened up Prototype itself and looked up the following lines in Element#clonePosition
```
if (Element.getStyle(element, 'position') == 'absolute') {
		  parent = element.getOffsetParent();
		  delta = parent.viewportOffset();
		}
```
Following a hunch I wrapped this with a try catch block on IE to try the call a second time if an error is raised. That fix works and is the following code.
```
try {
		// delta [0,0] will do fine with position: fixed elements,
		// position:absolute needs offsetParent deltas
		if (Element.getStyle(element, 'position') == 'absolute') {
		  parent = element.getOffsetParent();
		  delta = parent.viewportOffset();
		}
	} catch (e) {
		// IE fails on first try and succeeds on subsequent tries. Why? Dunno.
		if (Prototype.Browser.IE) {
			if (Element.getStyle(element, 'position') == 'absolute') {
			  parent = element.getOffsetParent();
			  delta = parent.viewportOffset();
			}
		}
	}
```
The fix worked and doesn't break anything for Firefox 3, 2, Opera 9, or Safari 3. The fix is a bit of a kludge though - the problem it answers needs to be isolated in Element#getStyle for the final fix to the problem.

**Comment by savetheclocktower** [comment]
This got fixed.
