### ISSUE TITLE
Element#deepClone

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#199]
[previous lighthouse ticket #1177](https://prototype.lighthouseapp.com/projects/8886/tickets/1177-elementdeepclone) 
by Michael Morris

***
Could a #deepClone method be added that is equivalent to Element#clone(true). I personally am NOT a fan of magic constants and that's what this amounts to. I also think it's bad clone(true) needs to persist for backwards compatibility of course - but I'd rather have the code self document. Just compare.
```
var e = $('someElement').clone(true);
var f = $('someElement').deepClone();
```

**Comment by savetheclocktower** [comment]
Not going to add a new `Element` method that's just an alias of an existing behavior.
