### ISSUE TITLE
Observed elements should only be pushed to the `CACHE` if on IE

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#200]
[previous lighthouse ticket #1025](https://prototype.lighthouseapp.com/projects/8886/tickets/1025-observed-elements-should-only-be-pushed-to-the-cache-if-on-ie) 
by ronin-93814 (at lighthouseapp)

***
All observed elements are being pushed to the CACHE array. This array is used only on IE to be able to clean up the event listeners in the _destroyCache method, which is called upon window.onunload. This patch puts an if (Prototype.Browser.IE) around the invocation of CACHE.push(element); to save some memory on other browsers.

This ticket is related to #466 (Suppress memory leaks from Element.remove and Elemen.update).

**Comment by savetheclocktower** [comment]
We do this differently now.
