### ISSUE TITLE
update_helper will result in JS errors if loaded in browsers without console

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#205]
[previous lighthouse ticket #596](https://prototype.lighthouseapp.com/projects/8886/tickets/596-update_helper-will-result-in-js-errors-if-loaded-in-browsers-without-console) 
by jwheare

***

The UpdateHelper log method currently just calls console methods without checking to see if it exists. This should probably check to see it's defined first.

Patch here: http://github.com/jwheare/prototype/commit/b3b1cb071323234c889a563422e5f1308e12866c

**Comment by savetheclocktower** [comment]
Not worth fixing this. Doubt anyone still uses the update helper.
