### ISSUE TITLE
crash on content.evalScripts.bind(content).defer() in update, replace, replace_IE and insertContentAt

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#206]
[previous lighthouse ticket #1327](https://prototype.lighthouseapp.com/projects/8886/tickets/1327-crash-on-contentevalscriptsbindcontentdefer-in-update-replace-replace_ie-and-insertcontentat) 
by Dan Popescu

***

if content is null or '' then "content.evalScripts.bind(content).defer()" throws an error
I think it should be replaced with:
"content && content.evalScripts.bind(content).defer();"

**Comment by savetheclocktower** [comment]
Don't see how it throws an error when `content` is an empty string, and don't really care if it throws an error when `content` is `null`.
