### ISSUE TITLE
Latest prototype.js from github repo - exception in Opera

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#214]
[previous lighthouse ticket #1284](https://prototype.lighthouseapp.com/projects/8886/tickets/1284-latest-prototypejs-from-github-repo-exception-in-opera) 
by Victor

***
When using `document.on("click", ...)` and clicking with mouse on link to another page, Opera 11.52 throws exception on page unload:
```
Event thread: unload
Uncaught exception: TypeError: Cannot convert 'Event.cache' to object
Error thrown at line 6458, column 6 in <anonymous function>(event) in http://example.com/app/js/prototype-1.7.js:
    var element = Event.cache[uid].element;
```
Line 6458 is in createResponder():
```
  function createResponder(uid, eventName, handler) {
    if (Event._isCustomEvent(eventName))
      return createResponderForCustomEvent(uid, eventName, handler);
    if (isSimulatedMouseEnterLeaveEvent(eventName))
      return createMouseEnterLeaveResponder(uid, eventName, handler);

    return function(event) {
      var element = Event.cache[uid].element; // <- line 6458
      Event.extend(event, element);
      handler.call(element, event);
    };
  }
```
I traced this code in Opera Dragonfly and found that Opera unloads page and continues calling responder with MouseEvent when either Event.cache is set to null or uid is undefined (closure scope is destroyed).

**Comment by savetheclocktower** [comment]
Not going to try to track this down unless someone reports it against a newer version of Opera.
