### ISSUE TITLE
Element.clonePosition uses border-box-width/border-box-height

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#222]
[previous lighthouse ticket #1372](https://prototype.lighthouseapp.com/projects/8886/tickets/1372-elementcloneposition-uses-border-box-widthborder-box-height) 
by Victor

***
Element.clonePosition uses border-box-width and border-box-height to calculate dimensions of source element, but sets width and height of content.

In other words, it uses border-box model to get dimensions from source, but uses content-box model to set dimensions on target.

Example: http://jsfiddle.net/S6exj/ - DIVs will have different width after clonePosition().

In this example clonePosition() calculates width of source element including its content, padding and border (50px content + 2 x 5px padding + 2 x 1px border = 62px), and sets content-width of target to that value, but target itself has its own padding and border, and its resulting border-box-width will be not 62px but 74px. Cloning element's width and height becomes non-trivial task.

**Comment by savetheclocktower** [comment]
Fixed in 2514900f05deb9df5c84b24350f279ca9dc5e814; see #255.
