### ISSUE TITLE
viewportOffset - introduced redundant code in 1.7.0.0

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#232]
[previous lighthouse ticket #1191](https://prototype.lighthouseapp.com/projects/8886/tickets/1191-viewportoffset-introduced-redundant-code-in-1700) 
by Terry Johnson 

***
The element extension line here is new since 1.7_rc3 and does not appear to wrap the correct variable:
```javascript
  function viewportOffset(forElement) {
    element = $(element);
    var valueT = 0, valueL = 0, docBody = document.body;

    var element = forElement;
```
Suggested fix:
```javascript
  function viewportOffset(forElement) {
    var valueT = 0, valueL = 0, docBody = document.body;
    var element = $(forElement);
```

**Comment by savetheclocktower** [comment]
This got fixed in #87.
