### ISSUE TITLE
CSS selector IE7 problem with header HTML5 element

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#243]
[previous lighthouse ticket #1185](https://prototype.lighthouseapp.com/projects/8886/tickets/1185-css-selector-ie7-problem-with-header-html5-element) 
by Filippo Buratti

***
the problem occurs on the browser Internet Explorer version 6/7 only with the element HTML5 "header":
```javascript
// well use http://html5shiv.googlecode.com/svn/trunk/html5.js

// <header id="myheader">some content</header>
$$("header h2 a").invoke(blabla); // don't work
$$("#myheader h2 a").invoke(blabla); // work

//<nav>some content</nav><nav>some content</nav>"; 
// nav arent inside header #myheader
$$("nav").invoke("hide"); works at all
$$("header nav").invoke(blabla); // don't work
$$("#myheader nav").invoke(blabla); // work
```
better solution is to use current nwmatcher instead of sizzle, and all the selectors of the examples above work

**Comment by savetheclocktower** [comment]
Assuming that Sizzle has fixed this by now.
