### ISSUE TITLE
Can't initialize in specific version of Android browser

### ISSUE THREAD

**Issue by kamk** [sstephenson/prototype#246]
While it works in Android emulator (4.2.2) it doesn't on my physical device. The user agent is identified as: `Mozilla/5.0 (Linux; U; Android 4.2.2; cs-cz; M720G Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`

There are two errors, one upon loading the library:
```
prototype.js:2838
Uncaught TypeError: Cannot read property 'Simulated'
```
and other one when accessing element by $("..."):
```
prototype.js:2057
Uncaught TypeError: Object function Element(tagName, attributes) {
    attributes = attributes || {};
    tagName = tagName.toLowerCase();

    if (HAS_EXTENDED_CREATE_ELEMENT_SYNTAX && attributes.name) {
      tagName = '<' + tagName + ' name="' + attributes.name + '">';
      delete attributes.name;
      return Element.writeAttribute(document.createElement(tagName), attributes);
    }

    if (!ELEMENT_CACHE[tagName])
      ELEMENT_CACHE[tagName] = Element.extend(document.createElement(tagName));

    var node = shouldUseCreationCache(tagName, attributes) ?
     ELEMENT_CACHE[tagName].cloneNode(false) : document.createElement(tagName);

    return Element.writeAttribute(node, attributes);
  } has no method 'extend'
```

Prototype is of version 1.7.2. Could it be device's system browser is broken?

**Comment by savetheclocktower** [comment]
Android support is a minefield. If something works in a device simulator, it's nearly impossible to figure out exactly why it's failing on an actual device without owning the device in question. Hate to do this, but gotta close this one, at least until more people report it. :-(
