### ISSUE TITLE
clonePosition regression in 1.7.2 when scrolling page content

### ISSUE THREAD

**Issue by fnappey** [sstephenson/prototype#248]
On the same page, when I'm using de 1.7.0 version of Prototype and the Element.clonePosition to setup a sub menu position, it works all time.
Calling the version 1.7.2 instead, it works if I don't scroll in page. But as soon as I scroll, the effect of the clonePosition method to setup the vertical position of an element is bugy.
Tested on IE8 and last version of Chrome.
Thanks in advance.

**Comment by savetheclocktower** [comment]
Fixed in 2514900f05deb9df5c84b24350f279ca9dc5e814; see #255.
