### ISSUE TITLE
document.viewport.getHeight() off by 60 in iPhone

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#271]
[previous lighthouse ticket #1250](https://prototype.lighthouseapp.com/projects/8886/tickets/1250-documentviewportgetheight-off-by-60-in-iphone) 
by Nick Wing

***
I didn't see a ticket for this yet, apologies if I missed it.

When I call document.viewport.getHeight() in iPhone and the address bar is scrolled up to where it's hidden from the user, I get the wrong height. I get the height as if the address bar were still fully visible. Since the address bar is (currently) 60 pixels tall in iPhone Safari, the value is too small by 60.

For now I have:
```javascript
function getViewportHeight() {
  var vph = document.viewport.getHeight();
  return (window.innerHeight - 60 == vph ? window.innerHeight : vph); 
}
```
This is awfully fragile but I'm at a loss for a better way.

**Comment by savetheclocktower** [comment]
Only time I've heard about this. Closing until someone else reports or until I get a failing test case.
