### ISSUE TITLE
IE8 Memory Leak with no script or content, just Prototype >= 1.7.1.0

### ISSUE THREAD

**Issue by aura-geoff-viljoen** [sstephenson/prototype#275]
Given the following HTML, IE8 grows memory usage in the task manager by ~1mb per second:
```html
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=8">
	<script src="//ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js"></script>
	<meta http-equiv="refresh" content="1">
</head>
<body>
</body>
</html>
```

This occurs with IE8 version 8.0.7601.17514 supplied by Microsoft as a Virtualbox VM here:
https://www.modern.ie/en-gb/virtualization-tools (IE8, Win7, Build 20131127)

This does not occur when any of these conditions are met:
- Removing `<meta http-equiv="X-UA-Compatible" content="IE=8">`
- Changing the Prototype version to 1.7.0.0

Version 1.7.2.0 also exhibits this problem.

Does anyone know what may have changed in 1.7.1.0 onwards that may have caused this?

**Comment by savetheclocktower** [comment]
So I'm not sure what to do with this. It appears that setting `Element` to `null` fixes it, but that's a big gun to take out. At some point I'll see if I can narrow it down — whether it's a property of `Element` that leaks, or some closure created by one of the methods, or some weird third thing.

**Comment by savetheclocktower** [comment]
I think we're going to close this now that Microsoft is no longer supporting IE 8. The next version of Prototype will drop support for IE 8 as well.
