### ISSUE TITLE
HTTP PUT/PATCH Support, Bodies?

### ISSUE THREAD

**Issue by rye** [sstephenson/prototype#280]
I use exotic/standard HTTP methods, including PUT and PATCH.  Currently, these aren't supported by Prototype.  I think it'd be great if PUT and PATCH were both supported, since they're standard functions.  They function similarly to POST requests, but instead involve updates/changes to things instead of creation and fetching, which are what POST and GET are designed for, respectively.

To support, I'd recommend that the `Ajax.Request` `options` object no longer need the `postBody` attribute and instead consume a solid `body` attribute.  Since GET requests can have a body, too (and do, in my use-case), it'd be great if this was just always sent off.

I'm willing to help but I'm new to the project.  Anyone got any ideas on how to make this happen?  For now I'll just use core XHR's.

**Comment by qsiebers** [comment]
I've made a patch for this in the past for our product. It's only a code change without test cases, so it might require some work. I'll open a PR for it, so you can have a look at it and maybe use it as a starting point.
