### ISSUE TITLE
Is prototype js stil being actively developed or dead ?

### ISSUE THREAD

**Issue by kressly** [sstephenson/prototype#288]
HI 
I LOVE PROTOTYPE JS because i think it is easier and more comprehensive . However, i am very concerned about it's future. Is this project still being delopped or is it dead like scriptaculous ? Scriptaculous was one of the best that works with prototype but the owner had given up on it. Please is the same thing happenong with prototype ?

**Comment by savetheclocktower** [comment]
You'll notice there are recent commits. Development is slow, but the project is not dead.

Let's keep discussion out of the issue tracker.
