### ISSUE TITLE
Drop support for old IE

### ISSUE THREAD

**Issue by jdalton** [sstephenson/prototype#306]
@savetheclocktower 

On Jan 12, 2016 MS implements its [new support policy for IE browsers](https://support.microsoft.com/en-us/gp/microsoft-internet-explorer)
which is only the latest available IE for the OS.

![](https://cloud.githubusercontent.com/assets/4303/11510667/afbc61ee-9819-11e5-941b-8ea6ac044233.png)

With that in mind would you be open to dropping support for at least IE < 9 in a future release?

**Comment by savetheclocktower** [comment]
I'd certainly be open to it. At first it would likely just be ceasing to care whether a new change breaks something in IE 6; later on I can attempt to remove things that are no longer needed in newer IEs.

**Comment by jdalton** [comment]
> later on I can attempt to remove things that are no longer needed in newer IEs

Would you dig a PR?

**Comment by savetheclocktower** [comment]
Oh, sure, why not?

**Comment by savetheclocktower** [comment]
(a black cat crossed my path as I typed those words)

**Comment by kmoe** [comment]
Does anyone else get a bizarre `/en/en/en/en...` redirect loop when clicking on the new support policy link?

**Comment by jdalton** [comment]
@kmoe I've updated the link to remove the language preset.
