### ISSUE TITLE
Native Array.prototype.filter is overwritten by prototype

### ISSUE THREAD

**Issue by welluh** [sstephenson/prototype#337]
I'm using Magento 1.9.3 with PrototypeJS version 1.7. which defines an `Enumerable::findAll` and the `Enumerable` methods are mixed in with `Array.prototype`, but fails to check if `Array.prototype.filter` already exists. 

In the documentation [here](http://api.prototypejs.org/language/Array/prototype/filter/) it states that native method will not be overwritten.

The real issue here is that `Enumerable::findAll` doesn't support third argument to the callback function of `Array.prototype.filter()`.

Hope this issue could be fixed.

Kind regards,
-welluh-

**Comment by savetheclocktower** [comment]
Update to 1.7.3 to get this fix. Thanks!
