### ISSUE TITLE
Unable to build on Windows (no tar command)

### ISSUE THREAD

**Issue by laurinkeithdavis** [sstephenson/prototype#339]
Is there a way to workaround no tar command available on Windows to build this library?

c:\Github\prototype>rake package --trace
** Invoke package (first_time)
** Invoke c:/Github/prototype/pkg/prototype-1.7.3.tar.gz (first_time)
** Invoke c:/Github/prototype/pkg/prototype-1.7.3 (first_time, not_needed)
** Invoke CHANGELOG (first_time, not_needed)
** Invoke LICENSE (first_time, not_needed)
** Invoke README.markdown (first_time, not_needed)
** Invoke Rakefile (first_time, not_needed)
** Invoke dist (first_time)
** Execute dist
** Invoke doc_assets (first_time, not_needed)
** Invoke ext (first_time, not_needed)
** Invoke pkg (first_time, not_needed)
** Invoke src (first_time, not_needed)
** Invoke test (first_time)
** Invoke test:require (first_time)
** Execute test:require
** Invoke test:start (first_time)
** Invoke test:require
** Execute test:start
Starting unit test server...
Unit tests available at <http://127.0.0.1:4567/test/>

[2018-02-25 09:00:39] INFO  WEBrick 1.4.2
[2018-02-25 09:00:39] INFO  ruby 2.5.0 (2017-12-25) [x64-mingw32]
== Sinatra (v2.0.1) has taken the stage on 4567 for development with backup from WEBrick
[2018-02-25 09:00:39] INFO  WEBrick::HTTPServer#start: pid=26664 port=4567
== Sinatra has ended his set (crowd applauds)
[2018-02-25 09:00:40] INFO  going to shutdown ...
[2018-02-25 09:00:40] INFO  WEBrick::HTTPServer#start done.
** Execute test
** Invoke vendor (first_time, not_needed)
** Invoke dist/prototype.js (first_time, not_needed)
** Invoke src/constants.yml (first_time, not_needed)
** Invoke src/prototype (first_time, not_needed)
** Invoke src/prototype.js (first_time, not_needed)
** Invoke test/browser.html (first_time, not_needed)
** Invoke test/console.html (first_time, not_needed)
** Invoke test/functional (first_time, not_needed)
** Invoke test/unit (first_time, not_needed)
** Invoke CHANGELOG (not_needed)
** Invoke LICENSE (not_needed)
** Invoke README.markdown (not_needed)
** Invoke Rakefile (not_needed)
** Invoke dist
** Invoke doc_assets (not_needed)
** Invoke ext (not_needed)
** Invoke pkg (not_needed)
** Invoke src (not_needed)
** Invoke test
** Invoke vendor (not_needed)
** Invoke dist/prototype.js (not_needed)
** Invoke src/constants.yml (not_needed)
** Invoke src/prototype (not_needed)
** Invoke src/prototype.js (not_needed)
** Invoke test/browser.html (not_needed)
** Invoke test/console.html (not_needed)
** Invoke test/functional (not_needed)
** Invoke test/unit (not_needed)
** Execute c:/Github/prototype/pkg/prototype-1.7.3.tar.gz
cd c:/Github/prototype/pkg
**tar zcvf prototype-1.7.3.tar.gz prototype-1.7.3
rake aborted!
Command failed with status (127): [tar zcvf prototype-1.7.3.tar.gz prototype-...]**
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:57:in `sh'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/packagetask.rb:136:in `block (3 levels) in define'
C:/tools/ruby25/lib/ruby/2.5.0/fileutils.rb:122:in `chdir'
C:/tools/ruby25/lib/ruby/2.5.0/fileutils.rb:122:in `cd'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils_ext.rb:38:in `chdir'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/packagetask.rb:135:in `block (2 levels) in define'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
C:/tools/ruby25/bin/rake:31:in `load'
C:/tools/ruby25/bin/rake:31:in `<main>'
Tasks: TOP => package => c:/Github/prototype/pkg/prototype-1.7.3.tar.gz

**Comment by walterdavis** [comment]
You can also download from Github in Zip format. It's just a choice you make in their UI.

Walter

**Comment by savetheclocktower** [comment]
Yeah, and all that does is build a TAR — you can just do `rake dist` to build a distributable file. This is a low-priority thing now that [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) exists.

**Comment by laurinkeithdavis** [comment]
@walterdavis - Download what in Zip format? When I download that, the dist folder does not contain the dist file.

@savetheclocktower - Yea, I figured that out at some point and I love that Windows has WSL now, but my Linux is not near as good as my Windows. Still, I might try cause I need to learn. 

Thanks.

**Comment by walterdavis** [comment]
Ah. If you just need the finished JS code, get it from any of the major CDNs. Google has it, CDNJS has it, there are lots of ways to either hot-link it into your pages or download it and serve it yourself.

Walter

**Comment by laurinkeithdavis** [comment]
We use it on an Intranet site and therefore want Internet failure fault tolerance, so we want locally stored resources only.
