### ISSUE TITLE
Array.prototype.toJSON requires double parsing after stringify

### ISSUE THREAD

**Issue by matanshiloah** [sstephenson/prototype#344]
When prototype.js loads on page, stringifying an array required double parsing to convert back to array.
F.E:
`var a = [ 1 ];`
`var b = JSON.stringify(a);  // will output ""[1]"" (string of array to string) instead of "[1]" (array to string)`
`var c = JSON.parse(b);   // will output "[1]" (array to string) instead of [1] (array)`
`JSON.parse(c);    // will output [1] (array)`.
Found on potora.jp.

**Comment by savetheclocktower** [comment]
This is an issue from a very old version of Prototype. Updating to 1.7 should fix this.
