### ISSUE TITLE
Compatibility with RetroZilla

### ISSUE THREAD

**Issue by tobiastromm** [sstephenson/prototype#346]
Can this please work with https://github.com/rn10950/RetroZilla/ browser?

Thank you.

**Comment by walterdavis** [comment]
Do you know what the UserAgent string is for this browser? Does it identify itself as Mozilla or Netscape or something else? The code that Prototype.js uses to figure out which browser is in action is very simple, and can be found here: https://github.com/prototypejs/prototype/blob/master/src/prototype/prototype.js#L76 You'd need to look through that, compare how it switches on the navigator.userAgent property value, and ensure that something useful was passed to it so it didn't mis-identify your browser.

Walter

**Comment by tobiastromm** [comment]
Hi @walterdavis,

according to https://www.whatsmyua.info/, this is the UserAgent:

    * rawUa: Mozilla/5.0 (Windows; U; Windows NT 4.0; en-US; rv:1.8.1.24) Gecko/20190223 RetroZilla/2.2 SeaMonkey/1.1.19 Firefox/2.0.20
    * string:
    * family: SeaMonkey
    * major: 1
    * minor: 1
    * patch: 19
    * device: Other 0.0.0

**Comment by walterdavis** [comment]
Okay, so what happens when you use this browser with Prototype.js? Are you noticing parts of the framework that don't work for you? Is there any of your own code that you can share, which calls into Prototype, that is not behaving as you expect? Can you make a cut-down example that we could use to duplicate your results?

Walter

**Comment by tobiastromm** [comment]
This is a browser for old OS. Sometimes I have to use my Windows NT 4 to test something.

I trying to use www.papinho.com, prototype is used to load all the messages.

Just open it, select "SIM", type something and enter. Then type some message and press enter.

It will not load messages on the old browser.

**Comment by walterdavis** [comment]
This site is using jQuery, not Prototype. This list is for Prototype.js.

Walter

**Comment by tobiastromm** [comment]
@walterdavis,

sorry.

I am on the wrong place. I am using EventSource.  Just open a new topic on the right place, https://github.com/Yaffle/EventSource/issues/141.
