### ISSUE TITLE
Uncaught SyntaxError: unexpected token: ':'

### ISSUE THREAD

**Issue by kressly** [sstephenson/prototype#350]
Uncaught SyntaxError: unexpected token: ':'
    evalScripts https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:640
    wrapNative https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:1270
    evalScripts https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:640
    delay https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:434
prototype.js:3:12
    evalScripts https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:640
    map self-hosted:221
    wrapNative https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:1270
    evalScripts https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:640
    evalScripts self-hosted:1173
    delay https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js:434

**Comment by jwestbrook** [comment]
Can you provide more context to the error ?

All of the lines you identified are places where third party scripts are being wrapped or eval'd so there is a chance the syntax error is the evaluation of that script versus a syntax error in Prototype

**Comment by jwestbrook** [comment]
I'm closing this issue, if you need to re-open with more information please do.
