### ISSUE TITLE
https://api.prototypejs.org/ seems to be down.

### ISSUE THREAD

**Issue by HeuvelTop** [sstephenson/prototype#351]
I wanted to look into https://api.prototypejs.org/, but I get a github status page: "Site not found"

**Comment by skotfred** [comment]
The certificate for that domain is for *.github.com - as such the browser is seeing a mismatch. Even if you bypass the warning you will see a 404 from Github. Was there a recent change to the DNS?

**Comment by jwestbrook** [comment]
Apologies for the docs being down, they are back up now.

**Comment by HeuvelTop** [comment]
Many thanks. Projotypjs is still very much my preferred framework. Thanks for keeping it available.
