### ISSUE TITLE
prototype.js is causing chart.js to not work

### ISSUE THREAD

**Issue by judovana** [sstephenson/prototype#358]
Hello, this is most likely chartjs issue, but considering the severity of it, any feedback may be welcomed.

all the info and reproducers - https://github.com/chartjs/Chart.js/issues/11201

Long story short, if prototype.js is loaded by webpage - eg jenkins include it by default - it will make chart.js library not working, thus prohibiting any chartjs plugins to be doen for jenkins. Also as jenkins is strongly frozen on prototype.js, most likely unfixable in prototype.js, but you guys here may have some advices.

**Comment by MarkEWaite** [comment]
Prototype.js has been removed from Jenkins and from Jenkins plugins as of Jenkins weekly 2.426.  It will be removed from Jenkins LTS 2.426.1 when it releases 15 Nov 2023.

More information on the Prototype.js removal project is available in the [initial announcement blog post](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/) from May 2023 and in the [conclusion and summary blog post](https://www.jenkins.io/blog/2023/10/09/prototype-removed/) from Oct 2023.

**Comment by judovana** [comment]
tyvm sir!
